"""Generate OS-specific firewall rules to prevent proxy bypass.

Implements the hardening strategy from issue #33:
- Linux: iptables/nftables rules to block direct port-443 traffic
- macOS: pf rules to block direct port-443 traffic

Both approaches force all HTTPS traffic through the secretgate forward
proxy, preventing AI tools from bypassing the proxy by unsetting env vars.
"""

from __future__ import annotations

import platform
import shutil
from pathlib import Path

import structlog

logger = structlog.get_logger()

_PF_ANCHOR = "com.secretgate"
_PF_ANCHOR_FILE = Path("/etc/pf.anchors") / _PF_ANCHOR


def detect_os() -> str:
    """Return 'linux', 'macos', or 'unsupported'."""
    system = platform.system().lower()
    if system == "linux":
        return "linux"
    elif system == "darwin":
        return "macos"
    return "unsupported"


def _has_command(name: str) -> bool:
    return shutil.which(name) is not None


def generate_iptables_rules(
    proxy_port: int = 8083,
    uid: int | None = None,
    block_domains: list[str] | None = None,
) -> str:
    """Generate iptables rules to force traffic through the proxy.

    Args:
        proxy_port: The local forward proxy port to allow.
        uid: Restrict rules to this UID. If None, applies to all users.
        block_domains: If provided, only block these domains (resolved at
            generation time). If None, blocks all port-443 traffic.

    Returns:
        Shell script content with iptables commands.
    """
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by: secretgate harden --install",
        "# Prevents AI tools from bypassing the proxy by blocking direct HTTPS",
        "set -euo pipefail",
        "",
        "# Allow loopback (proxy traffic)",
        "iptables -A OUTPUT -o lo -j ACCEPT",
        "",
    ]

    uid_match = f" -m owner --uid-owner {uid}" if uid is not None else ""

    if block_domains:
        lines.append("# Block direct connections to specific domains")
        for domain in block_domains:
            lines.append(f"# {domain}")
            lines.append(
                f"iptables -A OUTPUT -p tcp --dport 443"
                f"{uid_match} -d {domain} -j REJECT --reject-with tcp-reset"
            )
        lines.append("")
    else:
        lines.append("# Block ALL direct outbound HTTPS connections")
        lines.append(
            f"iptables -A OUTPUT -p tcp --dport 443{uid_match} -j REJECT --reject-with tcp-reset"
        )
        lines.append("")

    lines.extend(
        [
            "# Allow proxy port",
            f"iptables -I OUTPUT -p tcp --dport {proxy_port} -d 127.0.0.1 -j ACCEPT",
            "",
            'echo "secretgate firewall rules installed."',
            f'echo "All HTTPS traffic must go through localhost:{proxy_port}"',
        ]
    )
    return "\n".join(lines)


def generate_iptables_uninstall(
    proxy_port: int = 8083,
    uid: int | None = None,
    block_domains: list[str] | None = None,
) -> str:
    """Generate iptables commands to remove the hardening rules."""
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by: secretgate harden --uninstall",
        "set -euo pipefail",
        "",
    ]

    uid_match = f" -m owner --uid-owner {uid}" if uid is not None else ""

    lines.append(f"iptables -D OUTPUT -p tcp --dport {proxy_port} -d 127.0.0.1 -j ACCEPT 2>/dev/null || true")

    if block_domains:
        for domain in block_domains:
            lines.append(
                f"iptables -D OUTPUT -p tcp --dport 443"
                f"{uid_match} -d {domain} -j REJECT --reject-with tcp-reset 2>/dev/null || true"
            )
    else:
        lines.append(
            f"iptables -D OUTPUT -p tcp --dport 443{uid_match}"
            f" -j REJECT --reject-with tcp-reset 2>/dev/null || true"
        )

    lines.append("")
    lines.append("iptables -D OUTPUT -o lo -j ACCEPT 2>/dev/null || true")
    lines.append("")
    lines.append('echo "secretgate firewall rules removed."')
    return "\n".join(lines)


def generate_pf_rules(proxy_port: int = 8083, username: str | None = None) -> str:
    """Generate macOS pf rules to force traffic through the proxy.

    Args:
        proxy_port: The local forward proxy port to allow.
        username: Restrict rules to this user. If None, applies to all users.

    Returns:
        pf rule content for the anchor file.
    """
    user_clause = f" user {username}" if username else ""
    lines = [
        "# secretgate hardening rules — generated by: secretgate harden",
        f"# Anchor: {_PF_ANCHOR}",
        "#",
        "# Blocks direct outbound HTTPS, forcing traffic through the proxy.",
        f"# Load with: sudo pfctl -a {_PF_ANCHOR} -f /etc/pf.anchors/{_PF_ANCHOR}",
        "",
        "# Allow traffic to the local proxy",
        f"pass out proto tcp from any to 127.0.0.1 port {proxy_port}",
        "",
        "# Block direct outbound HTTPS connections",
        f"block out proto tcp from any to any port 443{user_clause}",
    ]
    return "\n".join(lines)


def generate_pf_install_script(proxy_port: int = 8083, username: str | None = None) -> str:
    """Generate a shell script to install pf rules on macOS."""
    rules = generate_pf_rules(proxy_port, username)
    anchor_path = f"/etc/pf.anchors/{_PF_ANCHOR}"
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by: secretgate harden --install",
        "set -euo pipefail",
        "",
        "# Write anchor rules",
        f"cat > {anchor_path} << 'PF_RULES'",
        rules,
        "PF_RULES",
        "",
        "# Check if anchor is already in pf.conf",
        f'if ! grep -q "{_PF_ANCHOR}" /etc/pf.conf 2>/dev/null; then',
        f'    echo "anchor \\"{_PF_ANCHOR}\\"" >> /etc/pf.conf',
        f'    echo "load anchor \\"{_PF_ANCHOR}\\" from \\"{anchor_path}\\"" >> /etc/pf.conf',
        "fi",
        "",
        "# Load the rules",
        f"pfctl -a {_PF_ANCHOR} -f {anchor_path}",
        "pfctl -e 2>/dev/null || true",
        "",
        'echo "secretgate pf rules installed."',
        f'echo "All HTTPS traffic must go through localhost:{proxy_port}"',
    ]
    return "\n".join(lines)


def generate_pf_uninstall_script() -> str:
    """Generate a shell script to remove pf rules on macOS."""
    anchor_path = f"/etc/pf.anchors/{_PF_ANCHOR}"
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by: secretgate harden --uninstall",
        "set -euo pipefail",
        "",
        "# Flush the anchor rules",
        f"pfctl -a {_PF_ANCHOR} -F all 2>/dev/null || true",
        "",
        "# Remove anchor file",
        f"rm -f {anchor_path}",
        "",
        "# Note: does not remove lines from /etc/pf.conf automatically.",
        f'# To fully clean up, remove the "{_PF_ANCHOR}" lines from /etc/pf.conf.',
        "",
        'echo "secretgate pf rules removed."',
    ]
    return "\n".join(lines)
